### ISSUE TITLE
Fails on Kubeflow Pipelines swagger specification

### ISSUE THREAD

**Issue by danielnorberg** [outofcoffee/imposter#36]
https://github.com/kubeflow/pipelines/blob/master/backend/api/swagger/kfp_api_single_file.swagger.json

```
docker run -ti -p 8080:8080 \
    -v $(pwd)/config:/opt/imposter/config \
    outofcoffee/imposter-openapi \
    --configDir /opt/imposter/config

16:21:21 DEBUG c.g.i.s.ImposterLauncher - No plugins specified - attempting to load defaults
16:21:21 DEBUG c.g.i.s.ImposterVerticle - Initialising mock server
16:21:21 INFO  c.g.i.Imposter - Starting mock engine
16:21:21 DEBUG c.g.i.Imposter - Loading configuration file: /opt/imposter/config/openapi2-config.json
16:21:21 INFO  c.g.i.Imposter - Loaded 1 plugin configuration files from: [/opt/imposter/config]
16:21:21 DEBUG c.g.i.Imposter - Registered plugin com.gatehill.imposter.plugin.detector.PluginDetectorImpl
16:21:21 DEBUG c.g.i.Imposter - 1 plugins provided by com.gatehill.imposter.plugin.detector.PluginDetectorImpl
16:21:21 DEBUG c.g.i.Imposter - Registered plugin com.gatehill.imposter.plugin.openapi.OpenApiPluginImpl
16:21:21 INFO  c.g.i.Imposter - Loaded 2 plugins
16:21:22 DEBUG c.g.i.p.o.u.OpenApiVersionUtil - Using version: V2 parser for: /opt/imposter/config/kfp_api_single_file.swagger.json
16:21:22 DEBUG c.g.i.p.o.OpenApiPluginImpl - Adding mock endpoint: GET -> /apis/v1beta1/runs
16:21:22 DEBUG c.g.i.p.o.OpenApiPluginImpl - Adding mock endpoint: POST -> /apis/v1beta1/runs
16:21:22 DEBUG c.g.i.p.o.OpenApiPluginImpl - Adding mock endpoint: DELETE -> /apis/v1beta1/runs/:id
16:21:22 DEBUG c.g.i.p.o.OpenApiPluginImpl - Adding mock endpoint: POST -> /apis/v1beta1/runs/:id:archive
16:21:22 DEBUG c.g.i.p.o.OpenApiPluginImpl - Adding mock endpoint: POST -> /apis/v1beta1/runs/:id:unarchive
16:21:22 DEBUG c.g.i.p.o.OpenApiPluginImpl - Adding mock endpoint: GET -> /apis/v1beta1/runs/{run_id}
16:21:22 DEBUG c.g.i.p.o.OpenApiPluginImpl - Adding mock endpoint: GET -> /apis/v1beta1/runs/{run_id}/nodes/{node_id}/artifacts/{artifact_name}:read
java.util.regex.PatternSyntaxException: Illegal repetition near index 18
/apis/v1beta1/runs/{run_id}/nodes/{node_id}/artifacts/{artifact_name}(?<p0>[^/]+)
                  ^
	at java.util.regex.Pattern.error(Pattern.java:1957)
	at java.util.regex.Pattern.closure(Pattern.java:3159)
	at java.util.regex.Pattern.sequence(Pattern.java:2136)
	at java.util.regex.Pattern.expr(Pattern.java:1998)
	at java.util.regex.Pattern.compile(Pattern.java:1698)
	at java.util.regex.Pattern.<init>(Pattern.java:1351)
	at java.util.regex.Pattern.compile(Pattern.java:1028)
	at io.vertx.ext.web.impl.RouteImpl.createPatternRegex(RouteImpl.java:397)
	at io.vertx.ext.web.impl.RouteImpl.setPath(RouteImpl.java:353)
	at io.vertx.ext.web.impl.RouteImpl.<init>(RouteImpl.java:68)
	at io.vertx.ext.web.impl.RouterImpl.route(RouterImpl.java:89)
	at com.gatehill.imposter.plugin.openapi.OpenApiPluginImpl.lambda$handlePathOperations$4(OpenApiPluginImpl.java:134)
	at java.util.LinkedHashMap.forEach(LinkedHashMap.java:684)
	at com.gatehill.imposter.plugin.openapi.OpenApiPluginImpl.handlePathOperations(OpenApiPluginImpl.java:128)
	at com.gatehill.imposter.plugin.openapi.OpenApiPluginImpl.lambda$null$0(OpenApiPluginImpl.java:104)
	at java.util.LinkedHashMap.forEach(LinkedHashMap.java:684)
	at com.gatehill.imposter.plugin.openapi.OpenApiPluginImpl.lambda$configureRoutes$1(OpenApiPluginImpl.java:103)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at com.gatehill.imposter.plugin.openapi.OpenApiPluginImpl.configureRoutes(OpenApiPluginImpl.java:98)
	at com.gatehill.imposter.server.ImposterVerticle.lambda$configureRoutes$4(ImposterVerticle.java:86)
	at java.util.HashMap$Values.forEach(HashMap.java:981)
	at java.util.Collections$UnmodifiableCollection.forEach(Collections.java:1080)
	at com.gatehill.imposter.server.ImposterVerticle.configureRoutes(ImposterVerticle.java:86)
	at com.gatehill.imposter.server.ImposterVerticle.lambda$start$0(ImposterVerticle.java:50)
	at io.vertx.core.impl.ContextImpl.lambda$executeBlocking$1(ContextImpl.java:271)
	at io.vertx.core.impl.TaskQueue.lambda$new$0(TaskQueue.java:60)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
16:21:22 ERROR i.v.c.i.l.c.VertxIsolatedDeployer - Failed in deploying verticle
java.util.regex.PatternSyntaxException: Illegal repetition near index 18
/apis/v1beta1/runs/{run_id}/nodes/{node_id}/artifacts/{artifact_name}(?<p0>[^/]+)
                  ^
	at java.util.regex.Pattern.error(Pattern.java:1957) ~[?:1.8.0_212]
	at java.util.regex.Pattern.closure(Pattern.java:3159) ~[?:1.8.0_212]
	at java.util.regex.Pattern.sequence(Pattern.java:2136) ~[?:1.8.0_212]
	at java.util.regex.Pattern.expr(Pattern.java:1998) ~[?:1.8.0_212]
	at java.util.regex.Pattern.compile(Pattern.java:1698) ~[?:1.8.0_212]
	at java.util.regex.Pattern.<init>(Pattern.java:1351) ~[?:1.8.0_212]
	at java.util.regex.Pattern.compile(Pattern.java:1028) ~[?:1.8.0_212]
	at io.vertx.ext.web.impl.RouteImpl.createPatternRegex(RouteImpl.java:397) ~[imposter-openapi.jar:?]
	at io.vertx.ext.web.impl.RouteImpl.setPath(RouteImpl.java:353) ~[imposter-openapi.jar:?]
	at io.vertx.ext.web.impl.RouteImpl.<init>(RouteImpl.java:68) ~[imposter-openapi.jar:?]
	at io.vertx.ext.web.impl.RouterImpl.route(RouterImpl.java:89) ~[imposter-openapi.jar:?]
	at com.gatehill.imposter.plugin.openapi.OpenApiPluginImpl.lambda$handlePathOperations$4(OpenApiPluginImpl.java:134) ~[imposter-openapi.jar:?]
	at java.util.LinkedHashMap.forEach(LinkedHashMap.java:684) ~[?:1.8.0_212]
	at com.gatehill.imposter.plugin.openapi.OpenApiPluginImpl.handlePathOperations(OpenApiPluginImpl.java:128) ~[imposter-openapi.jar:?]
	at com.gatehill.imposter.plugin.openapi.OpenApiPluginImpl.lambda$null$0(OpenApiPluginImpl.java:104) ~[imposter-openapi.jar:?]
	at java.util.LinkedHashMap.forEach(LinkedHashMap.java:684) ~[?:1.8.0_212]
	at com.gatehill.imposter.plugin.openapi.OpenApiPluginImpl.lambda$configureRoutes$1(OpenApiPluginImpl.java:103) ~[imposter-openapi.jar:?]
	at java.util.ArrayList.forEach(ArrayList.java:1257) ~[?:1.8.0_212]
	at com.gatehill.imposter.plugin.openapi.OpenApiPluginImpl.configureRoutes(OpenApiPluginImpl.java:98) ~[imposter-openapi.jar:?]
	at com.gatehill.imposter.server.ImposterVerticle.lambda$configureRoutes$4(ImposterVerticle.java:86) ~[imposter-openapi.jar:?]
	at java.util.HashMap$Values.forEach(HashMap.java:981) ~[?:1.8.0_212]
	at java.util.Collections$UnmodifiableCollection.forEach(Collections.java:1080) ~[?:1.8.0_212]
	at com.gatehill.imposter.server.ImposterVerticle.configureRoutes(ImposterVerticle.java:86) ~[imposter-openapi.jar:?]
	at com.gatehill.imposter.server.ImposterVerticle.lambda$start$0(ImposterVerticle.java:50) ~[imposter-openapi.jar:?]
	at io.vertx.core.impl.ContextImpl.lambda$executeBlocking$1(ContextImpl.java:271) ~[imposter-openapi.jar:?]
	at io.vertx.core.impl.TaskQueue.lambda$new$0(TaskQueue.java:60) ~[imposter-openapi.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_212]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_212]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
java.util.regex.PatternSyntaxException: Illegal repetition near index 18
/apis/v1beta1/runs/{run_id}/nodes/{node_id}/artifacts/{artifact_name}(?<p0>[^/]+)
                  ^
	at java.util.regex.Pattern.error(Pattern.java:1957)
	at java.util.regex.Pattern.closure(Pattern.java:3159)
	at java.util.regex.Pattern.sequence(Pattern.java:2136)
	at java.util.regex.Pattern.expr(Pattern.java:1998)
	at java.util.regex.Pattern.compile(Pattern.java:1698)
	at java.util.regex.Pattern.<init>(Pattern.java:1351)
	at java.util.regex.Pattern.compile(Pattern.java:1028)
	at io.vertx.ext.web.impl.RouteImpl.createPatternRegex(RouteImpl.java:397)
	at io.vertx.ext.web.impl.RouteImpl.setPath(RouteImpl.java:353)
	at io.vertx.ext.web.impl.RouteImpl.<init>(RouteImpl.java:68)
	at io.vertx.ext.web.impl.RouterImpl.route(RouterImpl.java:89)
	at com.gatehill.imposter.plugin.openapi.OpenApiPluginImpl.lambda$handlePathOperations$4(OpenApiPluginImpl.java:134)
	at java.util.LinkedHashMap.forEach(LinkedHashMap.java:684)
	at com.gatehill.imposter.plugin.openapi.OpenApiPluginImpl.handlePathOperations(OpenApiPluginImpl.java:128)
	at com.gatehill.imposter.plugin.openapi.OpenApiPluginImpl.lambda$null$0(OpenApiPluginImpl.java:104)
	at java.util.LinkedHashMap.forEach(LinkedHashMap.java:684)
	at com.gatehill.imposter.plugin.openapi.OpenApiPluginImpl.lambda$configureRoutes$1(OpenApiPluginImpl.java:103)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at com.gatehill.imposter.plugin.openapi.OpenApiPluginImpl.configureRoutes(OpenApiPluginImpl.java:98)
	at com.gatehill.imposter.server.ImposterVerticle.lambda$configureRoutes$4(ImposterVerticle.java:86)
	at java.util.HashMap$Values.forEach(HashMap.java:981)
	at java.util.Collections$UnmodifiableCollection.forEach(Collections.java:1080)
	at com.gatehill.imposter.server.ImposterVerticle.configureRoutes(ImposterVerticle.java:86)
	at com.gatehill.imposter.server.ImposterVerticle.lambda$start$0(ImposterVerticle.java:50)
	at io.vertx.core.impl.ContextImpl.lambda$executeBlocking$1(ContextImpl.java:271)
	at io.vertx.core.impl.TaskQueue.lambda$new$0(TaskQueue.java:60)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by outofcoffee** [comment]
Thanks for the report @danielnorberg.

I've added a new test and improved the path parameter detection in 3e43235f63fc28a456d4ef505f2e37a77aeba462

**Comment by outofcoffee** [comment]
@danielnorberg this fix is pushed to the 'beta' Docker tag; please could you let me know if this fixes the issue?

**Comment by danielnorberg** [comment]
The beta image seems to work 👍

**Comment by outofcoffee** [comment]
Thanks @danielnorberg
