### ISSUE TITLE
Using openapi yaml files greater than 3mb results in error

### ISSUE THREAD

**Issue by satishvntap** [outofcoffee/imposter#371]
When trying to use imposter to run a mock server, it fails with error. This is because the openapi yaml file size is greater than 3mb.

Caused by: com.fasterxml.jackson.dataformat.yaml.JacksonYAMLParseException: The incoming YAML document exceeds the limit: 3145728 code points.

Stacktrace
05:49:14 DEBUG i.g.i.p.PluginManager - Loaded 6 plugin(s): [js-detector, store-detector, openapi, rest, js-nashorn-standalone, store-inmem]

05:49:16 ERROR i.v.c.i.l.c.VertxIsolatedDeployer - Failed in deploying verticle

java.lang.RuntimeException: Error preparsing specification: dev.yaml

at io.gatehill.imposter.plugin.openapi.service.SpecificationLoaderService.parseSpecification(SpecificationLoaderService.kt:86) ~[imposter-mock-openapi-3.15.0.jar:?]

at io.gatehill.imposter.plugin.openapi.OpenApiPluginImpl.parseSpecs(OpenApiPluginImpl.kt:166) ~[imposter-mock-openapi-3.15.0.jar:?]

at io.gatehill.imposter.plugin.openapi.OpenApiPluginImpl.configureRoutes(OpenApiPluginImpl.kt:136) ~[imposter-mock-openapi-3.15.0.jar:?]

at io.gatehill.imposter.Imposter.configureRoutes(Imposter.kt:205) ~[imposter-engine-3.15.0.jar:?]

at io.gatehill.imposter.Imposter.access$configureRoutes(Imposter.kt:85) ~[imposter-engine-3.15.0.jar:?]

at io.gatehill.imposter.Imposter$start$1.invokeSuspend(Imposter.kt:128) ~[imposter-engine-3.15.0.jar:?]

at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33) ~[kotlin-stdlib-1.8.10.jar:1.8.10-release-430(1.8.10)]

at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106) ~[kotlinx-coroutines-core-jvm-1.6.4.jar:?]

at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570) ~[kotlinx-coroutines-core-jvm-1.6.4.jar:?]

at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750) ~[kotlinx-coroutines-core-jvm-1.6.4.jar:?]

at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677) ~[kotlinx-coroutines-core-jvm-1.6.4.jar:?]

at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664) ~[kotlinx-coroutines-core-jvm-1.6.4.jar:?]

Caused by: com.fasterxml.jackson.dataformat.yaml.JacksonYAMLParseException: The incoming YAML document exceeds the limit: 3145728 code points.

at [Source: (StringReader); line: 85661, column: 103]

at com.fasterxml.jackson.dataformat.yaml.YAMLParser.nextToken(YAMLParser.java:424) ~[jackson-dataformat-yaml-2.14.2.jar:2.14.2]

at com.fasterxml.jackson.core.JsonParser.nextFieldName(JsonParser.java:1065) ~[jackson-core-2.14.2.jar:2.14.2]

at com.fasterxml.jackson.databind.deser.std.UntypedObjectDeserializerNR._deserializeNR(UntypedObjectDeserializerNR.java:230) ~[jackson-databind-2.14.2.jar:2.14.2]

at com.fasterxml.jackson.databind.deser.std.UntypedObjectDeserializerNR.deserialize(UntypedObjectDeserializerNR.java:70) ~[jackson-databind-2.14.2.jar:2.14.2]

at com.fasterxml.jackson.databind.deser.std.MapDeserializer._readAndBindStringKeyMap(MapDeserializer.java:623) ~[jackson-databind-2.14.2.jar:2.14.2]

at com.fasterxml.jackson.databind.deser.std.MapDeserializer.deserialize(MapDeserializer.java:449) ~[jackson-databind-2.14.2.jar:2.14.2]

at com.fasterxml.jackson.databind.deser.std.MapDeserializer.deserialize(MapDeserializer.java:32) ~[jackson-databind-2.14.2.jar:2.14.2]

at com.fasterxml.jackson.databind.deser.DefaultDeserializationContext.readRootValue(DefaultDeserializationContext.java:323) ~[jackson-databind-2.14.2.jar:2.14.2]

at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4730) ~[jackson-databind-2.14.2.jar:2.14.2]

at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3677) ~[jackson-databind-2.14.2.jar:2.14.2]

at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3645) ~[jackson-databind-2.14.2.jar:2.14.2]

at io.gatehill.imposter.plugin.openapi.service.SpecificationLoaderService.parseSpecification(SpecificationLoaderService.kt:84) ~[imposter-mock-openapi-3.15.0.jar:?]

... 11 more

Caused by: org.yaml.snakeyaml.error.YAMLException: The incoming YAML document exceeds the limit: 3145728 code points.

at org.yaml.snakeyaml.scanner.ScannerImpl.fetchMoreTokens(ScannerImpl.java:342) ~[snakeyaml-1.33.jar:?]

at org.yaml.snakeyaml.scanner.ScannerImpl.checkToken(ScannerImpl.java:263) ~[snakeyaml-1.33.jar:?]

at org.yaml.snakeyaml.parser.ParserImpl$ParseBlockMappingKey.produce(ParserImpl.java:662) ~[snakeyaml-1.33.jar:?]

at org.yaml.snakeyaml.parser.ParserImpl.peekEvent(ParserImpl.java:185) ~[snakeyaml-1.33.jar:?]

at org.yaml.snakeyaml.parser.ParserImpl.getEvent(ParserImpl.java:195) ~[snakeyaml-1.33.jar:?]

at com.fasterxml.jackson.dataformat.yaml.YAMLParser.nextToken(YAMLParser.java:418) ~[jackson-dataformat-yaml-2.14.2.jar:2.14.2]

at com.fasterxml.jackson.core.JsonParser.nextFieldName(JsonParser.java:1065) ~[jackson-core-2.14.2.jar:2.14.2]

at com.fasterxml.jackson.databind.deser.std.UntypedObjectDeserializerNR._deserializeNR(UntypedObjectDeserializerNR.java:230) ~[jackson-databind-2.14.2.jar:2.14.2]

at com.fasterxml.jackson.databind.deser.std.UntypedObjectDeserializerNR.deserialize(UntypedObjectDeserializerNR.java:70) ~[jackson-databind-2.14.2.jar:2.14.2]

at com.fasterxml.jackson.databind.deser.std.MapDeserializer._readAndBindStringKeyMap(MapDeserializer.java:623) ~[jackson-databind-2.14.2.jar:2.14.2]

at com.fasterxml.jackson.databind.deser.std.MapDeserializer.deserialize(MapDeserializer.java:449) ~[jackson-databind-2.14.2.jar:2.14.2]

at com.fasterxml.jackson.databind.deser.std.MapDeserializer.deserialize(MapDeserializer.java:32) ~[jackson-databind-2.14.2.jar:2.14.2]

at com.fasterxml.jackson.databind.deser.DefaultDeserializationContext.readRootValue(DefaultDeserializationContext.java:323) ~[jackson-databind-2.14.2.jar:2.14.2]

at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4730) ~[jackson-databind-2.14.2.jar:2.14.2]

at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3677) ~[jackson-databind-2.14.2.jar:2.14.2]

at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3645) ~[jackson-databind-2.14.2.jar:2.14.2]

at io.gatehill.imposter.plugin.openapi.service.SpecificationLoaderService.parseSpecification(SpecificationLoaderService.kt:84) ~[imposter-mock-openapi-3.15.0.jar:?]

**Comment by outofcoffee** [comment]
Thanks for raising this @satishvntap.

It looks like we could make this limit configurable via an environment variable if that works for you?

**Comment by satishvntap** [comment]
Thank you for the quick response. Yes. A configurable environment variable should work fine for us.

**Comment by satishvntap** [comment]
The yaml file we are using is 14mb. We tried to set the value to 15728640. It doesn't seem to the values for 15mb. However, when we tried values 10485760 or 11485760. It seems to consider the values and we did encounter failure because our yaml size is 14mb.

**Comment by outofcoffee** [comment]
Hi @satishvntap, the underlying library with the limit is SnakeYAML. The change was introduced in [release 1.32](https://bitbucket.org/snakeyaml/snakeyaml/wiki/Changes) - the [code comments](https://bitbucket.org/snakeyaml/snakeyaml/src/72dfa9f1074abe2b8a6c8776bee4476b0aed02e3/src/main/java/org/yaml/snakeyaml/LoaderOptions.java#lines-139) also say:

> Please be aware that byte limit depends on the encoding

If the file encoding has two bytes per character, then you will need double the code point size.
