### ISSUE TITLE
Running "imposter up -t jvm" requires administrator rights

### ISSUE THREAD

**Issue by hilsonp** [outofcoffee/imposter#380]
```
imposter version
imposter-cli 0.32.1
imposter-engine 3.17.2
engine-output 3.17.2
```

Running `imposter up -t jvm` on Windows 11 (with openjdk version "11.0.19" 2023-04-18 LTS) , without running it as administrator gives an error because "C:\WINDOWS\\vertx-cache" is not writable.

```
C:\Users\XXX\Documents\projects\imposter>imposter up foo\bar\v1 -t jvm --log-level debug
time="2023-04-27T20:00:40+02:00" level=debug msg="engine binary '3.17.2' already present"
WARNING: sun.reflect.Reflection.getCallerClass is not supported. This will impact performance.
20:00:54 ERROR i.g.i.c.ImposterLauncher - Error starting server
java.lang.IllegalStateException: Unable to create folder at path 'C:\WINDOWS\\vertx-cache'
        at io.vertx.core.file.impl.FileCache.setupCacheDir(FileCache.java:61) ~[imposter-3.17.2.jar:?]
        at io.vertx.core.file.impl.FileCache.setupCache(FileCache.java:31) ~[imposter-3.17.2.jar:?]
        at io.vertx.core.file.impl.FileResolverImpl.<init>(FileResolverImpl.java:67) ~[imposter-3.17.2.jar:?]
        at io.vertx.core.impl.VertxBuilder.initFileResolver(VertxBuilder.java:338) ~[imposter-3.17.2.jar:?]
        at io.vertx.core.impl.VertxBuilder.init(VertxBuilder.java:278) ~[imposter-3.17.2.jar:?]
        at io.vertx.core.impl.launcher.commands.BareCommand.startVertx(BareCommand.java:224) ~[imposter-3.17.2.jar:?]
        at io.vertx.core.impl.launcher.commands.BareCommand.run(BareCommand.java:192) ~[imposter-3.17.2.jar:?]
        at io.vertx.core.impl.launcher.commands.RunCommand.run(RunCommand.java:246) ~[imposter-3.17.2.jar:?]
        at io.vertx.core.impl.launcher.VertxCommandLauncher.execute(VertxCommandLauncher.java:248) ~[imposter-3.17.2.jar:?]
        at io.vertx.core.impl.launcher.VertxCommandLauncher.dispatch(VertxCommandLauncher.java:383) ~[imposter-3.17.2.jar:?]
        at io.vertx.core.impl.launcher.VertxCommandLauncher.dispatch(VertxCommandLauncher.java:346) ~[imposter-3.17.2.jar:?]
        at io.gatehill.imposter.cmd.LifecycleAwareLauncher.dispatch(LifecycleAwareLauncher.kt:57) ~[imposter-3.17.2.jar:?]
        at io.gatehill.imposter.cmd.ImposterLauncher.startServer(ImposterLauncher.kt:202) ~[imposter-3.17.2.jar:?]
        at io.gatehill.imposter.cmd.ImposterLauncher.<init>(ImposterLauncher.kt:136) ~[imposter-3.17.2.jar:?]
        at io.gatehill.imposter.cmd.ImposterLauncher$Companion.main(ImposterLauncher.kt:123) ~[imposter-3.17.2.jar:?]
        at io.gatehill.imposter.cmd.ImposterLauncher.main(ImposterLauncher.kt) ~[imposter-3.17.2.jar:?]
Caused by: java.nio.file.AccessDeniedException: C:\WINDOWS\vertx-cache-862a18f7-49c2-4627-a495-388bfe559591
        at sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:89) ~[?:?]
        at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:103) ~[?:?]
        at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:108) ~[?:?]
        at sun.nio.fs.WindowsFileSystemProvider.createDirectory(WindowsFileSystemProvider.java:509) ~[?:?]
        at java.nio.file.Files.createDirectory(Files.java:690) ~[?:?]
        at java.nio.file.Files.createAndCheckIsDirectory(Files.java:797) ~[?:?]
        at java.nio.file.Files.createDirectories(Files.java:783) ~[?:?]
        at io.vertx.core.file.impl.FileCache.setupCacheDir(FileCache.java:53) ~[imposter-3.17.2.jar:?]
        ... 15 more
time="2023-04-27T20:01:12+02:00" level=fatal msg="timed out waiting for status endpoint to return HTTP 200 at http://localhost:8080/system/status"
```

I tried setting the cache directory:
- by doing an `SET IMPOSTER_CACHE_DIR=C:\Temp\`
- by adding `IMPOSTER_CACHE_DIR=C:\Temp\` into C:\Users\XXX\Documents\projects\imposter\.env
- by adding `IMPOSTER_CACHE_DIR=C:\Temp\` into C:\Users\XXX\Documents\projects\imposter\foo\bar\v1\.env
- by using `imposter up foo\bar\v1 -t jvm --log-level debug -e IMPOSTER_CACHE_DIR`

This didn't help.

Can you help me as I need to run this on someone's Windows laptop without administrator rights.

I thought that since imposter is released for Windows, this is ment to work.
https://github.com/gatehill/imposter-cli/releases

Thank you in advance.

Edit:
I see in the `imposter up --help` the `--enable-file-cache` option.
It is enabled by default but then... how to disable it ? There is no `--disable-file-cache`

**Comment by outofcoffee** [comment]
Hi @hilsonp, thank you for the issue report.

The file cache directory looks like it's picking up the wrong path as you flagged - specifically the `C:\WINDOWS\\vertx-cache` path in the error message.

The mechanism for determining this cache directory is defined within the Vert.x framework here: https://github.com/eclipse-vertx/vert.x/blob/master/src/main/java/io/vertx/core/file/FileSystemOptions.java#L39-L48

This comment appears to describe the logic:

```java
/**
 * The default file caching dir. If the system property {@code "vertx.cacheDirBase"} is set, then this is the value
 * If not, then the system property {@code java.io.tmpdir} is taken or {code .} if not set. suffixed with {@code vertx-cache}.
 */
  ```

I think we'd need to understand if the issue you're seeing is a bug in Vert.x or something environment specific, however, in the meantime, please could you try setting:

```
JAVA_TOOL_OPTIONS="-Dvertx.cacheDirBase=C:\Temp\vertx-cache"
```

Alternatively, this might also do the trick:

```
JAVA_TOOL_OPTIONS="-Djava.io.tmpdir=C:\Temp"
```

**Comment by hilsonp** [comment]
On Win11 (openjdk version "11.0.19" 2023-04-18 LTS), both environment variables solve the problem.

It would be nice to be able to set this through the .imposter\config.yaml
but otherwise, we will manage it using the environment variable.

I think anyone running imposter on Windows will fall into this trap ;-)

**Comment by outofcoffee** [comment]
Thank you for reporting back. I think it would make sense for us to set `vertx.cacheDirBase` for Windows users automatically.
