### ISSUE TITLE
Set `vertx.cacheDirBase` for Windows users automatically

### ISSUE THREAD

**Issue by outofcoffee** [outofcoffee/imposter#397]
Addresses #380

**Comment by outofcoffee** [comment]
Done in [v3.21.1](https://github.com/outofcoffee/imposter/releases).

**Comment by hilsonp** [comment]
I'm afraid this is not working in 3.22.0
```
C:\Users\ME\Documents\imposter>imposter up csesd\inscriptionV1
time="2023-06-08T13:02:34+02:00" level=debug msg="engine binary '3.22.0' already present"
WARNING: sun.reflect.Reflection.getCallerClass is not supported. This will impact performance.
13:02:37 ERROR i.g.i.c.ImposterLauncher - Error starting server
java.nio.file.AccessDeniedException: C:\WINDOWS\vertx-cache4096637815448725095
        at sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:89) ~[?:?]
        at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:103) ~[?:?]
        at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:108) ~[?:?]
        at sun.nio.fs.WindowsFileSystemProvider.createDirectory(WindowsFileSystemProvider.java:509) ~[?:?]
        at java.nio.file.Files.createDirectory(Files.java:690) ~[?:?]
        at java.nio.file.TempFileHelper.create(TempFileHelper.java:135) ~[?:?]
        at java.nio.file.TempFileHelper.createTempDirectory(TempFileHelper.java:172) ~[?:?]
        at java.nio.file.Files.createTempDirectory(Files.java:1007) ~[?:?]
        at io.gatehill.imposter.cmd.LifecycleAwareLauncher.<init>(LifecycleAwareLauncher.kt:63) ~[imposter-3.22.0.jar:?]        at io.gatehill.imposter.cmd.ImposterLauncher.startServer(ImposterLauncher.kt:202) ~[imposter-3.22.0.jar:?]
        at io.gatehill.imposter.cmd.ImposterLauncher.<init>(ImposterLauncher.kt:136) ~[imposter-3.22.0.jar:?]
        at io.gatehill.imposter.cmd.ImposterLauncher$Companion.main(ImposterLauncher.kt:123) ~[imposter-3.22.0.jar:?]
        at io.gatehill.imposter.cmd.ImposterLauncher.main(ImposterLauncher.kt) ~[imposter-3.22.0.jar:?]
```

**Comment by outofcoffee** [comment]
Hi @hilsonp, thanks for the feedback. This change has been reverted in v3.22.1.

Looks like we'll need to look at an alternative way to crack this.

The log output above suggests Java things your temp directory is `C:\WINDOWS`.

Would you mind showing the output of this command from the command line?

```
echo %TEMP%
```

**Comment by hilsonp** [comment]
Hi,

`echo %TEMP%` shows: `C:\Users\ME\AppData\Local\Temp`

The 3.22.1 seems ok:
```
C:\Users\ME\Documents\imposter>imposter up csesd\inscriptionV1
time="2023-06-12T09:09:54+02:00" level=debug msg="downloading https://github.com/outofcoffee/imposter/releases/download/v3.22.1/imposter.jar"
Picked up JAVA_TOOL_OPTIONS: "-Dvertx.cacheDirBase=C:\Temp\vertx-cache"
WARNING: sun.reflect.Reflection.getCallerClass is not supported. This will impact performance.
09:11:54 INFO  i.g.i.Imposter - Starting mock engine 3.22.1
09:11:54 DEBUG i.g.i.c.u.ConfigUtil - Loading configuration file: C:\Users\ME\Documents\imposter\csesd\inscriptionV1\inscriptionV1-config.yaml
09:11:56 DEBUG i.g.i.p.PluginManager - Loaded 7 plugin(s): [js-detector, store-detector, meta-detector, js-nashorn-standalone, store-inmem, config-detector, soap]
09:11:56 DEBUG i.g.i.p.s.p.VersionAwareWsdlParser - Using WSDL parser: V1 for: C:\Users\ME\Documents\imposter\csesd\inscriptionV1\wsdl\inscriptionV1_1.wsdl
09:11:56 DEBUG i.g.i.p.s.p.Wsdl1Parser - Discovered 12 schema(s) for WSDL: C:\Users\ME\Documents\imposter\csesd\inscriptionV1\wsdl\inscriptionV1_1.wsdl
09:11:57 DEBUG i.g.i.p.s.SoapPluginImpl - Adding mock endpoint: inscriptionV1SoapBinding -> HTTP /private/inscriptionV1
09:11:57 DEBUG i.g.i.s.g.s.GroovyScriptServiceImpl - Precompiling script: C:\Users\ME\Documents\imposter\csesd\inscriptionV1\publishInscriptionResponse.groovy
09:11:57 DEBUG i.g.i.s.g.s.GroovyScriptServiceImpl - Script: C:\Users\ME\Documents\imposter\csesd\inscriptionV1\publishInscriptionResponse.groovy compiled in 862ms
09:11:58 INFO  i.g.i.Imposter - Mock engine up and running on http://localhost:8080
time="2023-06-12T09:11:58+02:00" level=info msg="watching for changes to: C:\\Users\\ME\\Documents\\imposter\\csesd\\inscriptionV1"

time="2023-06-12T09:12:39+02:00" level=info msg="stopping mock engine"
time="2023-06-12T09:12:39+02:00" level=debug msg="shutting down"
```

For the sake of completeness ;-), if, on the same machine, I launch imposter in a MINGW64 (git bash), I get this:
```
ME@MYLAPTOP MINGW64 ~/Documents/imposter
$ ./imposter up ./csesd/inscriptionV1/
time="2023-06-12T09:09:54+02:00" level=debug msg="downloading https://github.com/outofcoffee/imposter/releases/download/v3.22.1/imposter.jar"
WARNING: sun.reflect.Reflection.getCallerClass is not supported. This will impact performance.
09:10:55 ERROR i.g.i.c.ImposterLauncher - Error starting server
java.lang.IllegalStateException: Unable to create folder at path 'C:\WINDOWS\\vertx-cache'
        at io.vertx.core.file.impl.FileCache.setupCacheDir(FileCache.java:61) ~[imposter-3.22.1.jar:?]
        at io.vertx.core.file.impl.FileCache.setupCache(FileCache.java:31) ~[imposter-3.22.1.jar:?]
        at io.vertx.core.file.impl.FileResolverImpl.<init>(FileResolverImpl.java:67) ~[imposter-3.22.1.jar:?]
        at io.vertx.core.impl.VertxBuilder.initFileResolver(VertxBuilder.java:338) ~[imposter-3.22.1.jar:?]
        at io.vertx.core.impl.VertxBuilder.init(VertxBuilder.java:278) ~[imposter-3.22.1.jar:?]
        at io.vertx.core.impl.launcher.commands.BareCommand.startVertx(BareCommand.java:224) ~[imposter-3.22.1.jar:?]
        at io.vertx.core.impl.launcher.commands.BareCommand.run(BareCommand.java:192) ~[imposter-3.22.1.jar:?]
        at io.vertx.core.impl.launcher.commands.RunCommand.run(RunCommand.java:246) ~[imposter-3.22.1.jar:?]
        at io.vertx.core.impl.launcher.VertxCommandLauncher.execute(VertxCommandLauncher.java:248) ~[imposter-3.22.1.jar:?]
        at io.vertx.core.impl.launcher.VertxCommandLauncher.dispatch(VertxCommandLauncher.java:383) ~[imposter-3.22.1.jar:?]
        at io.vertx.core.impl.launcher.VertxCommandLauncher.dispatch(VertxCommandLauncher.java:346) ~[imposter-3.22.1.jar:?]
        at io.gatehill.imposter.cmd.LifecycleAwareLauncher.dispatch(LifecycleAwareLauncher.kt:57) ~[imposter-3.22.1.jar:?]
        at io.gatehill.imposter.cmd.ImposterLauncher.startServer(ImposterLauncher.kt:202) ~[imposter-3.22.1.jar:?]
        at io.gatehill.imposter.cmd.ImposterLauncher.<init>(ImposterLauncher.kt:136) ~[imposter-3.22.1.jar:?]
        at io.gatehill.imposter.cmd.ImposterLauncher$Companion.main(ImposterLauncher.kt:123) ~[imposter-3.22.1.jar:?]
        at io.gatehill.imposter.cmd.ImposterLauncher.main(ImposterLauncher.kt) ~[imposter-3.22.1.jar:?]
Caused by: java.nio.file.AccessDeniedException: C:\WINDOWS\vertx-cache-d57027b4-fda3-44eb-a7f7-b77058d80960
        at sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:89) ~[?:?]
        at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:103) ~[?:?]
        at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:108) ~[?:?]
        at sun.nio.fs.WindowsFileSystemProvider.createDirectory(WindowsFileSystemProvider.java:509) ~[?:?]
        at java.nio.file.Files.createDirectory(Files.java:690) ~[?:?]
        at java.nio.file.Files.createAndCheckIsDirectory(Files.java:797) ~[?:?]
        at java.nio.file.Files.createDirectories(Files.java:783) ~[?:?]
        at io.vertx.core.file.impl.FileCache.setupCacheDir(FileCache.java:53) ~[imposter-3.22.1.jar:?]
        ... 15 more
time="2023-06-12T09:11:22+02:00" level=fatal msg="timed out waiting for status endpoint to return HTTP 200 at http://localhost:8080/system/status"

$ env|grep -i temp
ORIGINAL_TEMP=/tmp
TEMP=/tmp

$ cd /tmp

$ pwd -W
C:/Users/ME/AppData/Local/Temp
```

I really do not need a fix for this MINGW64 stuff. This is just for your information in case someone else report issues with vertx (so you know they may be in such MINGW64 environment).

**Comment by outofcoffee** [comment]
Thank you for being so thorough :)

**Comment by hilsonp** [comment]
3.23.2 does not seem to work :-/

C:\Users\ME\Documents\ESB\apigee-workspace\api-proxies\prov\soa>imposter up mock\prov-soa-csesd-imposterTest-v1\mock
time="2023-06-18T11:17:05+02:00" level=debug msg="downloading https://github.com/outofcoffee/imposter/releases/download/v3.23.2/imposter.jar"
11:17:15 ERROR i.g.i.c.ImposterLauncher - Error starting server
java.lang.IllegalStateException: Unable to create folder at path 'C:\WINDOWS\\vertx-cache'
        at io.vertx.core.file.impl.FileCache.setupCacheDir(FileCache.java:61) ~[imposter-3.23.2.jar:?]
        at io.vertx.core.file.impl.FileCache.setupCache(FileCache.java:31) ~[imposter-3.23.2.jar:?]
        at io.vertx.core.file.impl.FileResolverImpl.<init>(FileResolverImpl.java:67) ~[imposter-3.23.2.jar:?]
        at io.vertx.core.impl.VertxBuilder.initFileResolver(VertxBuilder.java:338) ~[imposter-3.23.2.jar:?]
        at io.vertx.core.impl.VertxBuilder.init(VertxBuilder.java:278) ~[imposter-3.23.2.jar:?]
