### ISSUE TITLE
NoSuchMethodError after jackson update

### ISSUE THREAD

**Issue by matejkobza** [outofcoffee/imposter#430]
Looks like there is an issue in v3.24.0 caused by jackson update:

`12:19:51 WARN  i.s.v.p.u.DeserializationUtils - Error snake-parsing yaml content
2023-06-26T12:19:51.926687295Z java.lang.NoSuchMethodError: org.yaml.snakeyaml.constructor.SafeConstructor: method 'void <init>()' not found
2023-06-26T12:19:51.926694689Z 	at io.swagger.v3.parser.util.DeserializationUtils$CustomSnakeYamlConstructor.<init>(DeserializationUtils.java:393) ~[swagger-parser-v3-2.1.9.jar:2.1.9]
2023-06-26T12:19:51.926699043Z 	at io.swagger.v3.parser.util.DeserializationUtils.readYamlTree(DeserializationUtils.java:207) ~[swagger-parser-v3-2.1.9.jar:2.1.9]
2023-06-26T12:19:51.926702665Z 	at io.swagger.v3.parser.util.DeserializationUtils.deserializeIntoTree(DeserializationUtils.java:143) ~[swagger-parser-v3-2.1.9.jar:2.1.9]
2023-06-26T12:19:51.926706310Z 	at io.swagger.v3.parser.OpenAPIV3Parser.readContents(OpenAPIV3Parser.java:165) ~[swagger-parser-v3-2.1.9.jar:2.1.9]
2023-06-26T12:19:51.926709947Z 	at io.swagger.v3.parser.OpenAPIV3Parser.readContents(OpenAPIV3Parser.java:104) ~[swagger-parser-v3-2.1.9.jar:2.1.9]
2023-06-26T12:19:51.926713513Z 	at io.gatehill.imposter.plugin.openapi.service.SpecificationLoaderService.parseSpecification(SpecificationLoaderService.kt:99) ~[imposter-mock-openapi-3.24.0.jar:?]
2023-06-26T12:19:51.926731358Z 	at io.gatehill.imposter.plugin.openapi.OpenApiPluginImpl.parseSpecs(OpenApiPluginImpl.kt:166) ~[imposter-mock-openapi-3.24.0.jar:?]
2023-06-26T12:19:51.926735842Z 	at io.gatehill.imposter.plugin.openapi.OpenApiPluginImpl.configureRoutes(OpenApiPluginImpl.kt:136) ~[imposter-mock-openapi-3.24.0.jar:?]
2023-06-26T12:19:51.926739493Z 	at io.gatehill.imposter.Imposter.configureRoutes(Imposter.kt:220) ~[imposter-engine-3.24.0.jar:?]
2023-06-26T12:19:51.926742963Z 	at io.gatehill.imposter.Imposter.access$configureRoutes(Imposter.kt:87) ~[imposter-engine-3.24.0.jar:?]
2023-06-26T12:19:51.926746382Z 	at io.gatehill.imposter.Imposter$start$1.invokeSuspend(Imposter.kt:134) ~[imposter-engine-3.24.0.jar:?]
2023-06-26T12:19:51.926749816Z 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33) ~[kotlin-stdlib-1.8.10.jar:1.8.10-release-430(1.8.10)]
2023-06-26T12:19:51.926753306Z 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106) ~[kotlinx-coroutines-core-jvm-1.6.4.jar:?]
2023-06-26T12:19:51.926756734Z 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570) ~[kotlinx-coroutines-core-jvm-1.6.4.jar:?]
2023-06-26T12:19:51.926761034Z 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750) ~[kotlinx-coroutines-core-jvm-1.6.4.jar:?]
2023-06-26T12:19:51.926764609Z 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677) ~[kotlinx-coroutines-core-jvm-1.6.4.jar:?]
2023-06-26T12:19:51.926768130Z 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664) ~[kotlinx-coroutines-core-jvm-1.6.4.jar:?]`

As a result of this swagger is not working at http://localhost:8080/_spec/. I have checked v.3.23.2 version and it is working okay. Looks like this issue is connected to jackson version update.

https://github.com/outofcoffee/imposter/commit/e19bb33737a217b9b6fe250771e8f0d985d441e4

**Comment by matejkobza** [comment]
![Screenshot 2023-06-26 at 14 51 55](https://github.com/outofcoffee/imposter/assets/3455842/b6a0d222-1e84-498a-9df9-e3e6e8b390cd)

**Comment by outofcoffee** [comment]
Thank you for the report and the PR. Merged and released in [v3.24.1](https://github.com/outofcoffee/imposter/releases)
