### ISSUE TITLE
No response with a non existing ID

### ISSUE THREAD

**Issue by cscetbon** [outofcoffee/imposter#54]
When an unknown ID is used imposter says it can't find it
```
14:59:28 ERROR i.g.i.p.s.SfdcPluginImpl - Account SObject with ID: 0015000000VALDtBBB not found
```
but it doesn't send a correct response to ForceApi and I get 
```
Exception in thread "main" java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:488)
	at Main_Scriptlet_fc96736f82df81e8$Companion.main(Main_Scriptlet_fc96736f82df81e8.kt:6)
	at Main_Scriptlet_fc96736f82df81e8.main(Main_Scriptlet_fc96736f82df81e8.kt)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.jetbrains.kotlin.runner.AbstractRunner.run(runners.kt:64)
	at org.jetbrains.kotlin.runner.Main.run(Main.kt:176)
	at org.jetbrains.kotlin.runner.Main.main(Main.kt:186)
Caused by: java.lang.RuntimeException: java.io.IOException: Stream closed
	at com.force.api.http.Http.send(Http.java:118)
	at com.force.api.ForceApi.apiRequest(ForceApi.java:499)
	at com.force.api.ForceApi.getSObject(ForceApi.java:206)
	at Scriptlet_fc96736f82df81e8.<init>(scriptlet.fc96736f82df81e8.kts:25)
	... 13 more
Caused by: java.io.IOException: Stream closed
	at java.base/java.io.BufferedInputStream.getInIfOpen(BufferedInputStream.java:165)
	at java.base/java.io.BufferedInputStream.read1(BufferedInputStream.java:290)
	at java.base/java.io.BufferedInputStream.read(BufferedInputStream.java:351)
	at java.base/java.io.FilterInputStream.read(FilterInputStream.java:107)
	at com.force.api.http.Http.readResponse(Http.java:57)
	at com.force.api.http.Http.send(Http.java:113)
	... 16 more
```

**Comment by outofcoffee** [comment]
Hi @cscetbon - it looks like Imposter sending the HTTP 404 status code might not be correct.

From [the documentation](https://developer.salesforce.com/docs/atlas.en-us.api_rest.meta/api_rest/errorcodes.htm), it appears a response like this might be appropriate:

```json
[
{
  "message" : "The requested resource does not exist",
  "errorCode" : "NOT_FOUND"
}
]
```

A few questions:

1. does this look correct to you?
2. what HTTP status code would you expect to be paired with this response body?

**Comment by outofcoffee** [comment]
Also, for reference - this is the ForceApi library implementation... notice the comment 😬 

![Screenshot 2021-11-02 at 20 11 32](https://user-images.githubusercontent.com/1248633/139945089-9342aa43-7a97-4341-84ba-72309e3d1f11.png)

**Comment by cscetbon** [comment]
hmm so it's coming from their API 🤔
