### ISSUE TITLE
Nashorn Load no longer working with Graal

### ISSUE THREAD

**Issue by Ober3550** [outofcoffee/imposter#581]
I can see that you've added the `polyglot.js.allowAllAccess` flag to the execution context but for some reason I still get a `Caused by: org.graalvm.polyglot.PolyglotException: Error: Operation is not allowed for: service/script.js`.  According to [https://www.graalvm.org/latest/reference-manual/js/NashornMigrationGuide/#allowIO](https://www.graalvm.org/latest/reference-manual/js/NashornMigrationGuide/#:~:text=of%20all%20classes.-,allowIO(),-%3A%20allow%20the%20guest) this flag is required to be set for load() to work. It's a bit weird to me that `polyglot.js.allowAllAccess` wouldn't allow this already?
I did notice that this seems to be a Context.eval error not just a ScriptEngine error? Maybe that has something to do with it?
```
Caused by: org.graalvm.polyglot.PolyglotException: Error: Operation is not allowed for: /opt/imposter/config/service/script.js
    at <js>.__run(Unnamed:46) ~[?:?]
    at <js>.:program(Unnamed:57) ~[?:?]
    at org.graalvm.polyglot.Context.eval(Context.java:425) ~[graal-sdk-22.3.5.jar:?]
    at io.gatehill.imposter.scripting.graalvm.service.GraalvmScriptServiceImpl.executeScript(GraalvmScriptServiceImpl.kt:122) ~[imposter-scripting-graalvm-3.40.0.jar:?]
    at io.gatehill.imposter.scripting.common.service.DelegatingJsScriptServiceImpl.executeScript(DelegatingJsScriptServiceImpl.kt:97) ~[imposter-scripting-common-3.40.0.jar:?]
    at io.gatehill.imposter.service.script.ScriptedResponseServiceImpl.execute(ScriptedResponseServiceImpl.kt:206) ~[imposter-engine-3.40.0.jar:?]
    at io.gatehill.imposter.service.script.ScriptedResponseServiceImpl.access$execute(ScriptedResponseServiceImpl.kt:79) ~[imposter-engine-3.40.0.jar:?]
    at io.gatehill.imposter.service.script.ScriptedResponseServiceImpl$determineResponseFromScript$scriptExecutor$1.invoke(ScriptedResponseServiceImpl.kt:161) ~[imposter-engine-3.40.0.jar:?]
    at io.gatehill.imposter.service.script.ScriptedResponseServiceImpl$determineResponseFromScript$scriptExecutor$1.invoke(ScriptedResponseServiceImpl.kt:160) ~[imposter-engine-3.40.0.jar:?]
    at io.gatehill.imposter.service.script.ScriptedResponseServiceImpl.determineResponseFromScript$lambda$7(ScriptedResponseServiceImpl.kt:168) ~[imposter-engine-3.40.0.jar:?]
    at io.micrometer.core.instrument.AbstractTimer.recordCallable(AbstractTimer.java:175) ~[micrometer-core-1.11.3.jar:1.11.3]
    at io.gatehill.imposter.service.script.ScriptedResponseServiceImpl.determineResponseFromScript(ScriptedResponseServiceImpl.kt:168) ~[imposter-engine-3.40.0.jar:?]
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
    at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
    at java.lang.reflect.Method.invoke(Unknown Source) ~[?:?]
    at com.google.inject.internal.DelegatingInvocationHandler.invoke(DelegatingInvocationHandler.java:50) ~[guice-5.1.0.jar:?]
    at com.sun.proxy.$Proxy48.determineResponseFromScript(Unknown Source) ~[?:?]
    at io.gatehill.imposter.model.steps.ScriptProcessingStep.execute(ScriptProcessingStep.kt:72) ~[imposter-engine-3.40.0.jar:?]
    at io.gatehill.imposter.service.ResponseRoutingServiceImpl.buildResponseBehaviour(ResponseRoutingServiceImpl.kt:146) ~[imposter-engine-3.40.0.jar:?]
    at io.gatehill.imposter.service.ResponseRoutingServiceImpl.route(ResponseRoutingServiceImpl.kt:90) ~[imposter-engine-3.40.0.jar:?]
    ... 12 more
```

**Comment by Ober3550** [comment]
Even though the default load() doesn't work since we have access to all the java objects I managed to get this to work as a temporary hack.
```
function load(filename) {
  var pathObj = java.nio.file.Paths.get(config.dir + "/" + filename);
  var bytesObj = java.nio.file.Files.readAllBytes(pathObj);
  var bytes = Java.from(bytesObj); // converting to JavaScript
  var content = String.fromCharCode.apply(null, bytes);
  return content;
}
eval(load("../script.js"));
print(test());
respond().withStatusCode(200).withContent(test());
```

**Comment by Ober3550** [comment]
Turns out it works fine if you use `ENV IMPOSTER_JS_PLUGIN=js-graal-compat` instead of `js-graal`. 
Leaving here for anyone who comes across this problem
