### ISSUE TITLE
Cannot Retrieve from Store on 4.0.3

### ISSUE THREAD

**Issue by daniel-klingensmith-jamf** [outofcoffee/imposter#623]
Running 4.0.3 with DynamoDB.
After POSTing an object which contains an array of objects to the store, I'm unable to retrieve its contents. I'm unable to view, update, or delete from the store at this point. I can see the objects in the DyanmoDB table. When I remove them manually from DynamoDB I can use the store again.  Here's what I used:
```
{
    "arrayField": [
        {
            "test": "value"
        }
    ]
}
```
Here's the stack trace:
```
2024-09-09 18:43:32 081fca6f-5674-488f-8cf6-b84ca8fbee09 ERROR i.g.i.s.HandlerServiceImpl - Unhandled routing exception for request: GET http://<redacted>.lambda-url.us-east-1.on.aws/system/store/callback-local
java.lang.RuntimeException: Route failed: HttpRoute(path=/system/store/{storeName}, regex=null, method=GET)
	at io.gatehill.imposter.awslambda.impl.LambdaServer.dispatch(LambdaServer.kt:99) ~[imposter-adapter-awslambda-4.0.3.jar:?]
	at io.gatehill.imposter.awslambda.HandlerV2.handleRequest(HandlerV2.kt:68) ~[imposter-adapter-awslambda-4.0.3.jar:?]
	at io.gatehill.imposter.awslambda.HandlerV2.handleRequest(HandlerV2.kt:57) ~[imposter-adapter-awslambda-4.0.3.jar:?]
	at lambdainternal.EventHandlerLoader$PojoHandlerAsStreamHandler.handleRequest(EventHandlerLoader.java:207) ~[aws-lambda-java-runtime-0.2.0.jar:?]
	at lambdainternal.EventHandlerLoader$2.call(EventHandlerLoader.java:925) ~[aws-lambda-java-runtime-0.2.0.jar:?]
	at lambdainternal.AWSLambda.startRuntime(AWSLambda.java:268) ~[aws-lambda-java-runtime-0.2.0.jar:?]
	at lambdainternal.AWSLambda.startRuntime(AWSLambda.java:207) ~[aws-lambda-java-runtime-0.2.0.jar:?]
	at lambdainternal.AWSLambda.main(AWSLambda.java:196) ~[aws-lambda-java-runtime-0.2.0.jar:?]
Caused by: java.lang.RuntimeException: Unhandled exception processing request [355a422f-92a1-4c76-9231-03e94a39adf8] GET http://<redacted>.lambda-url.us-east-1.on.aws/system/store/callback-local
	at io.gatehill.imposter.service.HandlerServiceImpl$handle$1.invokeSuspend(HandlerServiceImpl.kt:316) ~[imposter-engine-4.0.3.jar:?]
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33) ~[kotlin-stdlib-1.9.10.jar:1.9.10-release-459]
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108) ~[kotlinx-coroutines-core-jvm-1.7.3.jar:?]
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584) ~[kotlinx-coroutines-core-jvm-1.7.3.jar:?]
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793) ~[kotlinx-coroutines-core-jvm-1.7.3.jar:?]
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697) ~[kotlinx-coroutines-core-jvm-1.7.3.jar:?]
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684) ~[kotlinx-coroutines-core-jvm-1.7.3.jar:?]
Caused by: com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot deserialize value of type `java.util.LinkedHashMap<java.lang.Object,java.lang.Object>` from Array value (token `JsonToken.START_ARRAY`)
 at [Source: REDACTED (`StreamReadFeature.INCLUDE_SOURCE_IN_LOCATION` disabled); line: 1, column: 1]
	at com.fasterxml.jackson.databind.exc.MismatchedInputException.from(MismatchedInputException.java:59) ~[jackson-databind-2.17.0.jar:2.17.0]
	at com.fasterxml.jackson.databind.DeserializationContext.reportInputMismatch(DeserializationContext.java:1767) ~[jackson-databind-2.17.0.jar:2.17.0]
	at com.fasterxml.jackson.databind.DeserializationContext.handleUnexpectedToken(DeserializationContext.java:1541) ~[jackson-databind-2.17.0.jar:2.17.0]
	at com.fasterxml.jackson.databind.deser.std.StdDeserializer._deserializeFromArray(StdDeserializer.java:222) ~[jackson-databind-2.17.0.jar:2.17.0]
	at com.fasterxml.jackson.databind.deser.std.MapDeserializer.deserialize(MapDeserializer.java:457) ~[jackson-databind-2.17.0.jar:2.17.0]
	at com.fasterxml.jackson.databind.deser.std.MapDeserializer.deserialize(MapDeserializer.java:32) ~[jackson-databind-2.17.0.jar:2.17.0]
	at com.fasterxml.jackson.databind.deser.DefaultDeserializationContext.readRootValue(DefaultDeserializationContext.java:342) ~[jackson-databind-2.17.0.jar:2.17.0]
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4905) ~[jackson-databind-2.17.0.jar:2.17.0]
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3909) ~[jackson-databind-2.17.0.jar:2.17.0]
	at io.gatehill.imposter.store.dynamodb.DynamoDBStore.convertFromAttributeValue(DynamoDBStore.kt:211) ~[imposter-store-dynamodb-4.0.3.jar:?]
	at io.gatehill.imposter.store.dynamodb.DynamoDBStore.destructure(DynamoDBStore.kt:199) ~[imposter-store-dynamodb-4.0.3.jar:?]
	at io.gatehill.imposter.store.dynamodb.DynamoDBStore.loadAll(DynamoDBStore.kt:155) ~[imposter-store-dynamodb-4.0.3.jar:?]
	at io.gatehill.imposter.store.core.PrefixedKeyStore.loadAll(PrefixedKeyStore.kt:88) ~[imposter-store-common-4.0.3.jar:?]
	at io.gatehill.imposter.store.service.StoreRestApiServiceImpl$handleLoadAll$1.invoke(StoreRestApiServiceImpl.kt:111) ~[imposter-store-common-4.0.3.jar:?]
	at io.gatehill.imposter.store.service.StoreRestApiServiceImpl$handleLoadAll$1.invoke(StoreRestApiServiceImpl.kt:97) ~[imposter-store-common-4.0.3.jar:?]
	at io.gatehill.imposter.service.HandlerServiceImpl$wrapInFuture$1$1.invoke(HandlerServiceImpl.kt:149) ~[imposter-engine-4.0.3.jar:?]
	at io.gatehill.imposter.service.HandlerServiceImpl$wrapInFuture$1$1.invoke(HandlerServiceImpl.kt:149) ~[imposter-engine-4.0.3.jar:?]
	at io.gatehill.imposter.util.GlobalsKt.makeFuture(Globals.kt:74) ~[imposter-engine-4.0.3.jar:?]
	at io.gatehill.imposter.util.GlobalsKt.makeFuture$default(Globals.kt:71) ~[imposter-engine-4.0.3.jar:?]
	at io.gatehill.imposter.service.HandlerServiceImpl$wrapInFuture$1.invoke(HandlerServiceImpl.kt:149) ~[imposter-engine-4.0.3.jar:?]
	at io.gatehill.imposter.service.HandlerServiceImpl$wrapInFuture$1.invoke(HandlerServiceImpl.kt:148) ~[imposter-engine-4.0.3.jar:?]
	at io.gatehill.imposter.service.HandlerServiceImpl$handle$1.invokeSuspend(HandlerServiceImpl.kt:305) ~[imposter-engine-4.0.3.jar:?]
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33) ~[kotlin-stdlib-1.9.10.jar:1.9.10-release-459]
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108) ~[kotlinx-coroutines-core-jvm-1.7.3.jar:?]
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584) ~[kotlinx-coroutines-core-jvm-1.7.3.jar:?]
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793) ~[kotlinx-coroutines-core-jvm-1.7.3.jar:?]
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697) ~[kotlinx-coroutines-core-jvm-1.7.3.jar:?]
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684) ~[kotlinx-coroutines-core-jvm-1.7.3.jar:?]
```

**Comment by outofcoffee** [comment]
Hi @daniel-klingensmith-jamf, thanks for reporting this.

Are you able to provide a sequence of steps, such as using `curl` that gets you to this state?

e.g. step 1 - post `{...}` to `/stores/callback-local`, step 2...
